import { DetectedLibrary, DetectionContext, LibraryDetector } from '../shared/types.ts';
import { getWindow, getScriptUrls, reconcileVersionSignals } from './utils.ts';
import { extractVersionFromUrl } from '../analyzer/versionParser.ts';

export const angularDetector: LibraryDetector = {
  id: 'angular',
  name: 'Angular',
  npmPackage: '@angular/core',

  detect(context?: DetectionContext): DetectedLibrary | null {
    const win = getWindow(context);
    const scriptUrls = getScriptUrls(context);

    let runtimeSignal: { version?: string; evidence: string } | null = null;
    let urlSignal: { version?: string; evidence: string } | null = null;
    let metaSignal: { version?: string; evidence: string } | null = null;

    // 1. Check DOM for ng-version attribute (Angular 2+)
    // This is the most reliable version indicator emitted by Angular in production
    let domNgVersion: string | null = null;
    if (context?.domAttributes) {
      const ngAttr = context.domAttributes.find((a) => a.name.toLowerCase() === 'ng-version');
      if (ngAttr && ngAttr.value) {
        domNgVersion = ngAttr.value;
      }
    } else if (typeof document !== 'undefined') {
      const ngElement = document.querySelector('[ng-version]');
      if (ngElement) {
        domNgVersion = ngElement.getAttribute('ng-version');
      }
    }

    if (domNgVersion) {
      metaSignal = {
        version: domNgVersion,
        evidence: `DOM element [ng-version] attribute = ${domNgVersion}`
      };
    }

    // 2. Runtime inspection: window.ng (Angular modern) or window.angular (AngularJS)
    if (win?.ng && typeof win.ng === 'object') {
      const ver = win.ng.version?.full || win.ng.version;
      if (typeof ver === 'string') {
        runtimeSignal = {
          version: ver,
          evidence: `window.ng.version = ${ver}`
        };
      } else if (win.ng.coreTokens || win.ng.probe || win.ng.getComponent) {
        runtimeSignal = {
          evidence: 'window.ng runtime object detected'
        };
      }
    } else if (win?.angular && typeof win.angular === 'object') {
      const ver = win.angular.version?.full;
      if (typeof ver === 'string') {
        runtimeSignal = {
          version: ver,
          evidence: `window.angular.version.full = ${ver} (AngularJS)`
        };
      } else if (typeof win.angular.module === 'function') {
        runtimeSignal = {
          evidence: 'window.angular runtime module API detected'
        };
      }
    }

    // 3. Script URL inspection
    for (const url of scriptUrls) {
      if (/(?:@angular\/core|angular(?:\.min)?\.js|angular@)/i.test(url)) {
        const extracted = extractVersionFromUrl(url, '@angular/core') || extractVersionFromUrl(url, 'angular');
        if (extracted) {
          urlSignal = {
            version: extracted,
            evidence: `Script URL contains Angular version: ${url}`
          };
          break;
        } else if (!urlSignal) {
          urlSignal = {
            evidence: `Script URL references Angular: ${url}`
          };
        }
      }
    }

    if (!runtimeSignal && !urlSignal && !metaSignal) {
      return null;
    }

    // In Angular's case, dom [ng-version] is the actual runtime metadata generated by the framework
    const { finalVersion, evidence, conflictingSignals, confidence } =
      reconcileVersionSignals(runtimeSignal, urlSignal, null, metaSignal);

    return {
      name: 'Angular',
      npmPackage: '@angular/core',
      detectedVersion: finalVersion,
      evidence,
      confidence: metaSignal?.version || runtimeSignal?.version ? 'high' : confidence,
      conflictingSignals
    };
  }
};
